name: build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: give execution perms
      run: chmod +x ./gradlew

    - name: build
      run: ./gradlew build

    - name: upload plugin
      uses: actions/upload-artifact@v4
      with:
        name: paper-plugin-gradle
        path: build/libs/*.jar
